---
title: "Forward Stepwise"
output: html_document
---

Let's do Forward Stepwise Selection
----------------------------------

It's a greedy algorithm, produce a nested sequence of models. 

```{r}
library(ISLR2)
library(leaps)
```

Let's use the same regsubset function but change method to be "forward"

```{r}
Hitters=na.omit(Hitters)
regfit.fwd=regsubsets(Salary~., data=Hitters, nvmax = 19, method = "forward")
summary(regfit.fwd)
```

Let's plot Cp

```{r}
plot(regfit.fwd, scale="Cp")
```

- Models are nested
- Low cp with little variables in. 

Let's do Model selection with Validation set
--------------------------------------------


```{r}
# Let's check the dimensions
dim(Hitters)

set.seed(1)
# seq --> generates the sequence from 1 to n
# Take a sample of 180
train=sample(seq(263), 180, replace=FALSE)
train
regfit.fwd=regsubsets(Salary~., data=Hitters[train,], nvmax = 19, method = "forward")
```

Let's fit the model with the 180 observations. 

```{r}
# Set a vector with 19 slots ( 19 models )
val.errors=rep(NA,19)
# Check the negative in train
# Create a matrix to model salary as a function of all other variables
# Indexed by -train ( exclude observations in train )
x.test=model.matrix(Salary~.,data=Hitters[-train,])
```

**Let's make predictions for each model** 



```{r}

for (i in 1:19){
  # extract coeff for model size i 
  coefi=coef(regfit.fwd, id=i) 
  coefi
  # index cols by names of coefi vector then matrix multiplies by coefi vector
  pred=x.test[,names(coefi)] %*% coefi 
  # compute MSE
  val.errors[i]=mean((Hitters$Salary[-train]-pred)^2)
}
```

```{r}
# Plot the MSE
plot(sqrt(val.errors), ylab = "Root MSE", ylim = c(280,420), pch=19, type="b")
points(sqrt(regfit.fwd$rss[-1]/180),col='blue', pch=19, type="b")
legend("topright", legend=c("Training","Validation"),col = c("blue", "black"), pch=19)
```

- RSS is monotone decreasing. Each time we include variables, RSS should improve

```{r}
# let's use a function for prediction
predict.regsubsets=function(object, newdata, id,...){
  form=as.formula(object$call[[2]])
  mat=model.matrix(form, newdata)
  coefi=coef(object, id=id)
  mat[,names(coefi)] %*% coefi
}
```



